/// 🏛️ DOK-KEY 99 Grand Codex 6-Language Canonical Translation Registry
/// Zero Runtime Fallback Dictionary for 33 Divine Beasts (Zodiac) & 33 Mythic Gods (Myth)
/// Supported Locales: ko, en, ja, zh, de, hi

class CodexCanonicalData {
  static const Map<String, Map<String, String>> names = {
    'Z01': {
      'ko': '자(子) 쥐',
      'en': 'Rat (Zi)',
      'ja': '子(ね) 鼠',
      'zh': '子鼠',
      'de': 'Ratte (Zi)',
      'hi': 'चूहा (ज़ी)',
    },
    'Z02': {
      'ko': '축(丑) 소',
      'en': 'Ox (Chou)',
      'ja': '丑(うし) 牛',
      'zh': '丑牛',
      'de': 'Stier (Chou)',
      'hi': 'बैल (चोउ)',
    },
    'Z03': {
      'ko': '인(寅) 호랑이',
      'en': 'Tiger (Yin)',
      'ja': '寅(とら) 虎',
      'zh': '寅虎',
      'de': 'Tiger (Yin)',
      'hi': 'बाघ (यिन)',
    },
    'Z04': {
      'ko': '묘(卯) 토끼',
      'en': 'Rabbit (Mao)',
      'ja': '卯(う) 兎',
      'zh': '卯兔',
      'de': 'Hase (Mao)',
      'hi': 'खरगोश (माओ)',
    },
    'Z05': {
      'ko': '진(辰) 청룡',
      'en': 'Azure Dragon (Chen)',
      'ja': '辰(たつ) 青龍',
      'zh': '辰青龙',
      'de': 'Blauer Drache (Chen)',
      'hi': 'नीला ड्रैगन (चेन)',
    },
    'Z06': {
      'ko': '사(巳) 뱀',
      'en': 'Snake (Si)',
      'ja': '巳(み) 蛇',
      'zh': '巳蛇',
      'de': 'Schlange (Si)',
      'hi': 'सांप (सी)',
    },
    'Z07': {
      'ko': '오(午) 백마',
      'en': 'White Horse (Wu)',
      'ja': '午(うま) 白馬',
      'zh': '午白马',
      'de': 'Weißes Pferd (Wu)',
      'hi': 'सफेद घोड़ा (वू)',
    },
    'Z08': {
      'ko': '미(未) 양',
      'en': 'Sheep (Wei)',
      'ja': '未(ひつじ) 羊',
      'zh': '未羊',
      'de': 'Schaf (Wei)',
      'hi': 'भेड़ (वेई)',
    },
    'Z09': {
      'ko': '신(申) 원숭이',
      'en': 'Monkey (Shen)',
      'ja': '申(さる) 猿',
      'zh': '申猴',
      'de': 'Affe (Shen)',
      'hi': 'बंदर (शेन)',
    },
    'Z10': {
      'ko': '유(酉) 닭',
      'en': 'Rooster (You)',
      'ja': '酉(とり) 鶏',
      'zh': '酉鸡',
      'de': 'Hahn (You)',
      'hi': 'मुर्गा (यू)',
    },
    'Z11': {
      'ko': '술(戌) 개',
      'en': 'Dog (Xu)',
      'ja': '戌(いぬ) 犬',
      'zh': '戌犬',
      'de': 'Hund (Xu)',
      'hi': 'कुत्ता (शू)',
    },
    'Z12': {
      'ko': '해(亥) 황금돼지',
      'en': 'Golden Pig (Hai)',
      'ja': '亥(い) 黄金豚',
      'zh': '亥金猪',
      'de': 'Goldenes Schwein (Hai)',
      'hi': 'स्वर्ण सुअर (हाई)',
    },
    'Z13': {
      'ko': '해태',
      'en': 'Haetae',
      'ja': '獬豸 (ヘテ)',
      'zh': '獬豸',
      'de': 'Haechi',
      'hi': 'हेची',
    },
    'Z14': {
      'ko': '기린',
      'en': 'Qilin',
      'ja': '麒麟 (キリン)',
      'zh': '麒麟',
      'de': 'Qilin',
      'hi': 'किलिन',
    },
    'Z15': {
      'ko': '주작',
      'en': 'Vermilion Bird',
      'ja': '朱雀 (スザク)',
      'zh': '朱雀',
      'de': 'Zinnoberroter Vogel',
      'hi': 'सिंदूरी पक्षी',
    },
    'Z16': {
      'ko': '현무',
      'en': 'Black Tortoise',
      'ja': '玄武 (ゲンブ)',
      'zh': '玄武',
      'de': 'Schwarze Schildkröte',
      'hi': 'काला कछुआ',
    },
    'Z17': {
      'ko': '백록',
      'en': 'White Stag',
      'ja': '白鹿 (ハクロク)',
      'zh': '白鹿',
      'de': 'Weißer Hirsch',
      'hi': 'सफेद हिरण',
    },
    'Z18': {
      'ko': '봉황',
      'en': 'Fenghuang',
      'ja': '鳳凰 (ホウオウ)',
      'zh': '凤凰',
      'de': 'Fenghuang',
      'hi': 'फेंगहुआंग',
    },
    'Z19': {
      'ko': '삼족오',
      'en': 'Three-Legged Crow',
      'ja': '三足烏 (サンソクウ)',
      'zh': '三足乌',
      'de': 'Dreibeinige Krähe',
      'hi': 'तीन पैरों वाला कौआ',
    },
    'Z20': {
      'ko': '구미호',
      'en': 'Nine-Tailed Fox',
      'ja': '九尾狐 (キュウビコ)',
      'zh': '九尾狐',
      'de': 'Neunschwänziger Fuchs',
      'hi': 'नौ पूंछ वाली लोमड़ी',
    },
    'Z21': {
      'ko': '유니콘',
      'en': 'Unicorn',
      'ja': 'ユニコーン',
      'zh': '独角兽',
      'de': 'Einhorn',
      'hi': 'यूनिकॉर्न',
    },
    'Z22': {
      'ko': '삼목구',
      'en': 'Three-Eyed Dog',
      'ja': '三目犬 (サンモクケン)',
      'zh': '三目神犬',
      'de': 'Dreiäugiger Hund',
      'hi': 'त्रिनेत्र कुत्ता',
    },
    'Z23': {
      'ko': '가네샤',
      'en': 'Ganesha',
      'ja': 'ガネーシャ',
      'zh': '象头神',
      'de': 'Ganesha',
      'hi': 'भगवान गणेश',
    },
    'Z24': {
      'ko': '세베크',
      'en': 'Sobek',
      'ja': 'セベク',
      'zh': '索贝克',
      'de': 'Sobek',
      'hi': 'सोबेक',
    },
    'Z25': {
      'ko': '이무기',
      'en': 'Imoogi',
      'ja': 'イムギ',
      'zh': '螭龙',
      'de': 'Imoogi',
      'hi': 'इमूगी',
    },
    'Z26': {
      'ko': '어룡',
      'en': 'Fish-Dragon',
      'ja': '魚竜',
      'zh': '鳌鱼',
      'de': 'Fischdrache',
      'hi': 'मत्स्य ड्रैगन',
    },
    'Z27': {
      'ko': '스핑크스',
      'en': 'Sphinx',
      'ja': 'スフィンクス',
      'zh': '斯芬克斯',
      'de': 'Sphinx',
      'hi': 'स्फिंक्स',
    },
    'Z28': {
      'ko': '레비아탄',
      'en': 'Leviathan',
      'ja': 'レヴィアタン',
      'zh': '利维坦',
      'de': 'Leviathan',
      'hi': 'लेविआथन',
    },
    'Z29': {
      'ko': '묘두사',
      'en': 'Cat-Headed Snake',
      'ja': '猫頭蛇',
      'zh': '猫头蛇',
      'de': 'Katzenkopfschlange',
      'hi': 'बिल्ली-सिर सांप',
    },
    'Z30': {
      'ko': '삼족섬',
      'en': 'Three-Legged Toad',
      'ja': '三足蟾',
      'zh': '三足金蟾',
      'de': 'Dreibeinige Kröte',
      'hi': 'त्रिपाद मेंढक',
    },
    'Z31': {
      'ko': '그리핀',
      'en': 'Griffin',
      'ja': 'グリフォン',
      'zh': '狮鹫',
      'de': 'Greif',
      'hi': 'ग्रिफिन',
    },
    'Z32': {
      'ko': '피닉스',
      'en': 'Phoenix',
      'ja': 'フェニックス',
      'zh': '不死鸟',
      'de': 'Phönix',
      'hi': 'अमर फीनिक्स',
    },
    'Z33': {
      'ko': '케찰코아틀',
      'en': 'Quetzalcoatl',
      'ja': 'ケツァルコアトル',
      'zh': '羽蛇神',
      'de': 'Quetzalcoatl',
      'hi': 'क्वेत्ज़ालकोआत्ल',
    },
    'M01': {
      'ko': '산신령',
      'en': 'Mountain God (Sansin)',
      'ja': '山神 (サンシン)',
      'zh': '山神',
      'de': 'Berggeist (Sansin)',
      'hi': 'पर्वत देवता (सांसिन)',
    },
    'M02': {
      'ko': '저승사자',
      'en': 'Grim Reaper (Jeoseungsaja)',
      'ja': '冥府の使者',
      'zh': '阴差冥使',
      'de': 'Sensenmann (Jeoseungsaja)',
      'hi': 'यमदूत',
    },
    'M03': {
      'ko': '옥황상제',
      'en': 'Jade Emperor',
      'ja': '玉皇上帝',
      'zh': '玉皇大帝',
      'de': 'Jade-Kaiser',
      'hi': 'इंद्र / जेड सम्राट',
    },
    'M04': {
      'ko': '염라대왕',
      'en': 'King Yama',
      'ja': '閻魔大王',
      'zh': '阎罗大王',
      'de': 'König Yama',
      'hi': 'यमराज',
    },
    'M05': {
      'ko': '마고할미',
      'en': 'Mago Halmi (Earth Mother)',
      'ja': '麻姑 (マゴ) 祖母',
      'zh': '麻姑仙女',
      'de': 'Mago Halmi',
      'hi': 'मागो दादी',
    },
    'M06': {
      'ko': '바리데기',
      'en': 'Princess Bari',
      'ja': 'バリ公主',
      'zh': '钵里公主',
      'de': 'Prinzessin Bari',
      'hi': 'राजकुमारी बारी',
    },
    'M07': {
      'ko': '삼신할머니',
      'en': 'Samshin Grandmother',
      'ja': '三神ハルモニ',
      'zh': '三神奶奶',
      'de': 'Samshin-Großmutter',
      'hi': 'सामशिन दादी',
    },
    'M08': {
      'ko': '용왕',
      'en': 'Dragon King',
      'ja': '龍王',
      'zh': '四海龙王',
      'de': 'Drachenkönig',
      'hi': 'सागर राजा',
    },
    'M09': {
      'ko': '터줏대감',
      'en': 'Teoju Daegam',
      'ja': '屋敷神',
      'zh': '宅地神',
      'de': 'Hausgeist',
      'hi': 'गृह रक्षक देवता',
    },
    'M10': {
      'ko': '제우스',
      'en': 'Zeus',
      'ja': 'ゼウス',
      'zh': '宙斯',
      'de': 'Zeus',
      'hi': 'ज़्यूस',
    },
    'M11': {
      'ko': '포세이돈',
      'en': 'Poseidon',
      'ja': 'ポセイドン',
      'zh': '波塞冬',
      'de': 'Poseidon',
      'hi': 'पोसीडॉन',
    },
    'M12': {
      'ko': '하데스',
      'en': 'Hades',
      'ja': 'ハデス',
      'zh': '哈迪斯',
      'de': 'Hades',
      'hi': 'हेड्स',
    },
    'M13': {
      'ko': '토르',
      'en': 'Thor',
      'ja': 'トール',
      'zh': '托尔',
      'de': 'Thor',
      'hi': 'थोर',
    },
    'M14': {
      'ko': '오딘',
      'en': 'Odin',
      'ja': 'オーディン',
      'zh': '奥丁',
      'de': 'Odin',
      'hi': 'ओडिन',
    },
    'M15': {
      'ko': '아테나',
      'en': 'Athena',
      'ja': 'アテナ',
      'zh': '雅典娜',
      'de': 'Athene',
      'hi': 'एथेना',
    },
    'M16': {
      'ko': '아폴론',
      'en': 'Apollo',
      'ja': 'アポロン',
      'zh': '阿波罗',
      'de': 'Apollon',
      'hi': 'अपोलो',
    },
    'M17': {
      'ko': '로키',
      'en': 'Loki',
      'ja': 'ロキ',
      'zh': '洛基',
      'de': 'Loki',
      'hi': 'लोकी',
    },
    'M18': {
      'ko': '발키리',
      'en': 'Valkyrie',
      'ja': 'ヴァルキリー',
      'zh': '女武神',
      'de': 'Walküre',
      'hi': 'वाल्किरी',
    },
    'M19': {
      'ko': '붓다',
      'en': 'Buddha',
      'ja': '釈迦如来 (ブッダ)',
      'zh': '佛陀',
      'de': 'Buddha',
      'hi': 'भगवान बुद्ध',
    },
    'M20': {
      'ko': '관음보살',
      'en': 'Guanyin (Avalokiteshvara)',
      'ja': '観音菩薩',
      'zh': '观音菩萨',
      'de': 'Guanyin',
      'hi': 'माता गुआनयिन',
    },
    'M21': {
      'ko': '가네샤',
      'en': 'Ganesha',
      'ja': '歓喜天 (ガネーシャ)',
      'zh': '象头神',
      'de': 'Ganesha',
      'hi': 'भगवान गणेश',
    },
    'M22': {
      'ko': '시바',
      'en': 'Shiva',
      'ja': 'シヴァ',
      'zh': '湿婆',
      'de': 'Shiva',
      'hi': 'भगवान शिव',
    },
    'M23': {
      'ko': '인드라',
      'en': 'Indra',
      'ja': '帝釈天 (インドラ)',
      'zh': '因陀罗',
      'de': 'Indra',
      'hi': 'देवराज इंद्र',
    },
    'M24': {
      'ko': '라',
      'en': 'Ra',
      'ja': '太陽神ラー',
      'zh': '拉(太阳神)',
      'de': 'Ra',
      'hi': 'सूर्य देव रा',
    },
    'M25': {
      'ko': '오시리스',
      'en': 'Osiris',
      'ja': 'オシリス',
      'zh': '奥西里斯',
      'de': 'Osiris',
      'hi': 'ओसिरिस',
    },
    'M26': {
      'ko': '바스테트',
      'en': 'Bastet',
      'ja': 'バステト',
      'zh': '巴斯特',
      'de': 'Bastet',
      'hi': 'बास्तेत',
    },
    'M27': {
      'ko': '아누비스',
      'en': 'Anubis',
      'ja': 'アヌビス',
      'zh': '阿努比斯',
      'de': 'Anubis',
      'hi': 'अनुबिस',
    },
    'M28': {
      'ko': '대천사 미카엘',
      'en': 'Archangel Michael',
      'ja': '大天使ミカエル',
      'zh': '大天使米迦勒',
      'de': 'Erzengel Michael',
      'hi': 'महादूत माइकल',
    },
    'M29': {
      'ko': '대천사 가브리엘',
      'en': 'Archangel Gabriel',
      'ja': '大天使ガブリエル',
      'zh': '大天使加百列',
      'de': 'Erzengel Gabriel',
      'hi': 'महादूत गेब्रियल',
    },
    'M30': {
      'ko': '대천사 라파엘',
      'en': 'Archangel Raphael',
      'ja': '大天使ラファエル',
      'zh': '大天使拉斐尔',
      'de': 'Erzengel Raphael',
      'hi': 'महादूत राफेल',
    },
    'M31': {
      'ko': '대천사 우리엘',
      'en': 'Archangel Uriel',
      'ja': '大天使ウリエル',
      'zh': '大天使乌列尔',
      'de': 'Erzengel Uriel',
      'hi': 'महादूत उरीएल',
    },
    'M32': {
      'ko': '수호천사',
      'en': 'Guardian Angel',
      'ja': '守護天使',
      'zh': '守护天使',
      'de': 'Schutzengel',
      'hi': 'रक्षक देवदूत',
    },
    'M33': {
      'ko': '모이라이',
      'en': 'Moirai',
      'ja': 'モイライ',
      'zh': '命运三女神',
      'de': 'Moiren',
      'hi': 'भाग्य की देवियां (मोइरा)',
    },
  };

  static const Map<String, Map<String, String>> titles = {
    'Z01': {
      'ko': '지혜와 재물의 전령',
      'en': 'Messenger of Wisdom & Wealth',
      'ja': '知恵と財運の伝令',
      'zh': '智慧与财富的使者',
      'de': 'Bote von Weisheit & Reichtum',
      'hi': 'ज्ञान और धन का संदेशवाहक',
    },
    'Z02': {
      'ko': '우직함과 성실의 대지',
      'en': 'Earth of Sincerity & Tenacity',
      'ja': '実直と誠実の大地',
      'zh': '笃实与诚信的大地',
      'de': 'Erde der Beständigkeit',
      'hi': 'निष्ठा और दृढ़ता की भूमि',
    },
    'Z03': {
      'ko': '용맹과 벽사의 군주',
      'en': 'Monarch of Valor & Ward',
      'ja': '勇猛と破邪の君主',
      'zh': '勇猛与辟邪之君',
      'de': 'Herrscher des Mutes & Schutzes',
      'hi': 'साहस और सुरक्षा का अधिपति',
    },
    'Z04': {
      'ko': '민첩과 도약의 달빛',
      'en': 'Moonlight of Agility & Leap',
      'ja': '敏捷と跳躍の月光',
      'zh': '灵动与跃升的月光',
      'de': 'Mondlicht der Gewandtheit',
      'hi': 'स्फूर्ति और छलांग की चांदनी',
    },
    'Z05': {
      'ko': '천상과 조화의 인도자',
      'en': 'Guide of Heavens & Harmony',
      'ja': '天上と調和の導き手',
      'zh': '苍穹与和谐之引路人',
      'de': 'Führer des Himmels & der Harmonie',
      'hi': 'स्वर्ग और सद्भाव का मार्गदर्शक',
    },
    'Z06': {
      'ko': '변혁과 직관의 불꽃',
      'en': 'Flame of Intuition & Renewal',
      'ja': '変革と直感の炎',
      'zh': '蜕变与直觉的灵火',
      'de': 'Flamme der Intuition',
      'hi': 'परिवर्तन और अंतर्ज्ञान की ज्योति',
    },
    'Z07': {
      'ko': '열정과 질주의 백마',
      'en': 'Steed of Passion & Gallop',
      'ja': '情熱と疾走の白馬',
      'zh': '奔腾与热忱的白马',
      'de': 'Ross der Leidenschaft',
      'hi': 'उत्साह और रफ्तार का घोड़ा',
    },
    'Z08': {
      'ko': '평화와 온화함을 잇는 순백의 영수',
      'en': 'Gentle Spirit of Peace',
      'ja': '平和と温和を結ぶ純白の霊獣',
      'zh': '传递和平温润的纯白瑞兽',
      'de': 'Sanfter Geist des Friedens',
      'hi': 'शांति और सौम्यता का प्रतीक',
    },
    'Z09': {
      'ko': '기지와 재능의 번뜩임',
      'en': 'Spark of Wit & Talent',
      'ja': '機知と才知の閃き',
      'zh': '机敏与才华之灵光',
      'de': 'Funke des Witzes & Talents',
      'hi': 'हाजिरजवाबी और प्रतिभा की चमक',
    },
    'Z10': {
      'ko': '여명을 깨우는 빛의 파수꾼',
      'en': 'Sentinel Awakening the Dawn',
      'ja': '黎明を告げる光の番人',
      'zh': '破晓晨光的报晓司晨',
      'de': 'Wächter des Morgengrauens',
      'hi': 'भोर जगाने वाला प्रकाश का प्रहरी',
    },
    'Z11': {
      'ko': '충직함으로 터전을 지키는 파수견',
      'en': 'Loyal Guardian of the Hearth',
      'ja': '忠義で家を守る番犬',
      'zh': '尽忠护家的镇宅灵犬',
      'de': 'Treuer Wächter des Heims',
      'hi': 'घर की रक्षा करने वाला वफादार कुत्ता',
    },
    'Z12': {
      'ko': '풍요와 대복의 결실',
      'en': 'Harvest of Abundance & Great Fortune',
      'ja': '豊かさと大福の実り',
      'zh': '丰饶与大福之圆满',
      'de': 'Ernte von Fülle & Großem Glück',
      'hi': 'समृद्धि और अपार सौभाग्य का फल',
    },
    'Z13': {
      'ko': '정의를 가리는 벽사의 영물',
      'en': 'Divine Beast of Justice & Ward',
      'ja': '正義を見極める破邪の霊獣',
      'zh': '明辨是非之辟邪神兽',
      'de': 'Geistwesen der Gerechtigkeit',
      'hi': 'न्याय और रक्षा का दिव्य प्राणी',
    },
    'Z14': {
      'ko': '태평성대를 알리는 성수',
      'en': 'Auspicious Beast of Peaceful Eras',
      'ja': '太平の世を告げる聖獣',
      'zh': '告太平盛世之仁兽',
      'de': 'Heiliges Wesen des Friedens',
      'hi': 'शांति और समृद्धि का पावन जीव',
    },
    'Z15': {
      'ko': '남방을 수호하는 불사조',
      'en': 'Guardian Phoenix of the South',
      'ja': '南方を守護する不死鳥',
      'zh': '镇守南方之炽火朱雀',
      'de': 'Phönix des Südens',
      'hi': 'दक्षिण का रक्षक अमर पक्षी',
    },
    'Z16': {
      'ko': '북방의 장수와 북극성',
      'en': 'North Star of Longevity',
      'ja': '北方の長寿と北極星',
      'zh': '北方长寿与极星之主',
      'de': 'Nordstern des Langen Lebens',
      'hi': 'दीर्घायु और उत्तर का ध्रुव तारा',
    },
    'Z17': {
      'ko': '신선이 타는 불로장생의 성수',
      'en': 'Immortal Mount of Longevity',
      'ja': '仙人が乗る不老長寿の聖獣',
      'zh': '仙人所乘不老长生之灵鹿',
      'de': 'Reittier der Unsterblichkeit',
      'hi': 'अमर मुनियों की पावन सवारी',
    },
    'Z18': {
      'ko': '태평성대의 상징',
      'en': 'Crowning Herald of Prosperity',
      'ja': '泰平の世の象徴',
      'zh': '华贵至尊之太平灵凤',
      'de': 'Symbol Edler Harmonie',
      'hi': 'समृद्धि और सम्मान का शिखर',
    },
    'Z19': {
      'ko': '태양 속에 깃든 세 발 까마귀',
      'en': 'Embodied Sun Messenger',
      'ja': '太陽に宿る三本足の烏',
      'zh': '浴日而生之三足神乌',
      'de': 'Dreibeinige Sonnenkrähe',
      'hi': 'सूर्य में वास करने वाला दिव्य पक्षी',
    },
    'Z20': {
      'ko': '천 년의 지혜를 품은 영호',
      'en': 'Millennial Spirit Fox of Wisdom',
      'ja': '千年の知恵を宿す霊狐',
      'zh': '蕴纳千年造化之九尾仙狐',
      'de': 'Geistfuchs Jahrtausendealter Weisheit',
      'hi': 'हजार वर्ष की बुद्धि वाली लोमड़ी',
    },
    'Z21': {
      'ko': '치유와 순수의 외뿔 요정마',
      'en': 'Horn of Healing & Purity',
      'ja': '癒しと純粋の一角霊馬',
      'zh': '治愈与纯洁之一角仙兽',
      'de': 'Einhorn der Reinheit & Heilung',
      'hi': 'पवित्रता और उपचार का एक सींग वाला घोड़ा',
    },
    'Z22': {
      'ko': '귀신을 꿰뚫어보는 영안의 벽사견',
      'en': 'Clairvoyant Demon-Warding Hound',
      'ja': '邪霊を見通す霊眼の破邪犬',
      'zh': '洞察幽冥之辟邪三目神犬',
      'de': 'Dreiäugiger Geisterjäger',
      'hi': 'बुरी आत्माओं को देखने वाला कुत्ता',
    },
    'Z23': {
      'ko': '장애를 없애고 부를 부르는 지혜의 코끼리신',
      'en': 'Lord of Beginnings & Wisdom',
      'ja': '障害を除き富を呼ぶ歓喜天',
      'zh': '除障招财之象首智慧神',
      'de': 'Herr der Weisheit & Beseitiger von Hindernissen',
      'hi': 'विघ्नहर्ता और बुद्धि के देवता',
    },
    'Z24': {
      'ko': '풍요와 생명수를 다스리는 악어신',
      'en': 'Guardian of the Nile & Vitality',
      'ja': '豊穣と生命の水を司る鰐神',
      'zh': '掌管尼罗沃土之鳄首丰饶神',
      'de': 'Wächter der Lebensströme',
      'hi': 'जीवन के जल और उर्वरता का देवता',
    },
    'Z25': {
      'ko': '승천을 향해 정진하는 영룡',
      'en': 'Aspiring Dragon of Ascent',
      'ja': '昇天を目指し精進する霊竜',
      'zh': '蓄势登天之潜修螭龙',
      'de': 'Aufstrebender Drachengeist',
      'hi': 'आकाश छूने को प्रयासरत ड्रैगन',
    },
    'Z26': {
      'ko': '잉어가 용으로 변하는 등용문',
      'en': 'Carp Leaping the Dragon Gate',
      'ja': '鯉が龍へと化す登竜門',
      'zh': '鱼跃龙门化仙鳌',
      'de': 'Drachenfisch des Aufstiegs',
      'hi': 'ड्रैगन द्वार पार करती मछली',
    },
    'Z27': {
      'ko': '수수께끼와 지혜의 피라미드 수호수',
      'en': 'Keeper of Riddles & Vaults',
      'ja': '謎と知恵のピラミッド守護獣',
      'zh': '金字塔之谜与智慧守护神',
      'de': 'Hüter der Rätsel & Schätze',
      'hi': 'पहेलियों और खजाने का रक्षक',
    },
    'Z28': {
      'ko': '깊은 바다를 유영하는 푸른 숨결',
      'en': 'Titan of the Abyssal Ocean',
      'ja': '深海を遊泳する蒼き息吹',
      'zh': '遨游深海之浩瀚巨兽',
      'de': 'Herrscher der Meerestiefen',
      'hi': 'महासागर की गहराइयों का स्वामी',
    },
    'Z29': {
      'ko': '고양이 머리의 신비로운 영사',
      'en': 'Feline Serpent of Night Vision',
      'ja': '猫の頭を持つ神秘の霊蛇',
      'zh': '通灵祛魅之猫首神蛇',
      'de': 'Katzenköpfige Wächterschlange',
      'hi': 'बिल्ली के सिर वाला रहस्यमयी नाग',
    },
    'Z30': {
      'ko': '황금 엽전을 물고 오는 재물신',
      'en': 'Three-Legged Coin-Biting Toad',
      'ja': '金銭を咥えて訪れる財神',
      'zh': '吐宝咬钱之三足神蟾',
      'de': 'Münzfressende Glückskröte',
      'hi': 'मुंह में सोने का सिक्का दबाए मेंढक',
    },
    'Z31': {
      'ko': '황금과 보물을 지키는 사자독수리',
      'en': 'Guardian of Royal Treasures',
      'ja': '黄金と秘宝を守る獅子鷲',
      'zh': '镇守王都金藏之狮鹫',
      'de': 'Hüter der Königsjuwelen',
      'hi': 'शाही खजाने का रक्षक ग्रिफिन',
    },
    'Z32': {
      'ko': '불꽃 속에서 부활하는 영생의 신조',
      'en': 'Bird of Resurrection & Eternal Flame',
      'ja': '炎より蘇る永遠の神鳥',
      'zh': '浴火重生之不灭火鸟',
      'de': 'Vogel der Wiedergeburt',
      'hi': 'अग्नि से पुनर्जन्म लेने वाला अमर पक्षी',
    },
    'Z33': {
      'ko': '바람과 문명을 전하는 깃털뱀',
      'en': 'Feathered Serpent of Wind & Knowledge',
      'ja': '風と文明を告げる羽毛の蛇',
      'zh': '播撒微风与智慧之羽蛇',
      'de': 'Gefiederte Schlange des Wissens',
      'hi': 'पंखों वाला ज्ञान का सर्प',
    },
    'M01': {
      'ko': '영산을 품은 자애로운 신선',
      'en': 'Benevolent Immortal of Sacred Peaks',
      'ja': '霊山を抱く慈愛深き仙人',
      'zh': '怀抱灵山之慈爱山仙',
      'de': 'Gütiger Unsterblicher der Berge',
      'hi': 'पवित्र पर्वतों का कृपालु अमर संत',
    },
    'M02': {
      'ko': '인연의 길을 인도하는 길잡이',
      'en': 'Guide of Destiny & Karma',
      'ja': '因縁の道を導く先導役',
      'zh': '引渡因缘命途之执幡者',
      'de': 'Führer des Schicksals & Karmas',
      'hi': 'भाग्य और कर्म का मार्गदर्शक',
    },
    'M03': {
      'ko': '천계의 조화를 다스리는 천제',
      'en': 'Sovereign Ruler of Celestial Harmony',
      'ja': '天界の調和を司る天帝',
      'zh': '统御诸天万象之玉皇大帝',
      'de': 'Herrscher Himmlischer Harmonie',
      'hi': 'स्वर्ग के सर्वोच्च सम्राट',
    },
    'M04': {
      'ko': '공평무사한 명계의 판관',
      'en': 'Judge of Absolute Truth & Justice',
      'ja': '公平無私なる冥界の判官',
      'zh': '明镜高悬之冥府审判主',
      'de': 'Richter Über Wahrheit & Recht',
      'hi': 'धर्मराज और न्याय के स्वामी',
    },
    'M05': {
      'ko': '대지를 빚어낸 태초의 거인',
      'en': 'Primordial Titan of Creation',
      'ja': '大地を創り出した太初の巨人',
      'zh': '开辟洪荒大地之始祖神母',
      'de': 'Urmutter der Erdgestaltung',
      'hi': 'सृष्टि रचने वाली आदि देवी',
    },
    'M06': {
      'ko': '영혼을 치유하는 약속의 공주',
      'en': 'Princess of Soul Healing & Waters',
      'ja': '魂を癒す約束の公主',
      'zh': '救拔幽灵之灵水妙善公主',
      'de': 'Prinzessin des Heilenden Wassers',
      'hi': 'आत्माओं को शांति देने वाली राजकुमारी',
    },
    'M07': {
      'ko': '생명의 시작과 안녕을 품은 품',
      'en': 'Guardian Matron of Birth & Family',
      'ja': '命の誕生と安寧を抱く母胎',
      'zh': '赐子保生护佑阖家之慈母',
      'de': 'Schützerin des Neuen Lebens',
      'hi': 'संतान और परिवार की रक्षक',
    },
    'M08': {
      'ko': '사해 바다를 호령하는 해신',
      'en': 'Ruler of the Four Seas & Treasures',
      'ja': '四海の波を号令する海神',
      'zh': '号令四海八荒之龙皇',
      'de': 'Herrscher der Vier Meere',
      'hi': 'चारों समुद्रों का अधिपति',
    },
    'M09': {
      'ko': '보금자리를 든든히 지키는 가신',
      'en': 'Sentinel Deity of the Homestead',
      'ja': '住まいを固く守る屋敷神',
      'zh': '安宅固本之宅基尊神',
      'de': 'Schützer des Heimathafens',
      'hi': 'घर की सुख-शांति का रक्षक',
    },
    'M10': {
      'ko': '천공과 별빛을 다스리는 주신',
      'en': 'Lord of Thunder & Starlit Heavens',
      'ja': '天空と星光を統べる最高神',
      'zh': '统御九霄雷霆之奥林匹斯众神之王',
      'de': 'Herrscher des Olymp & Donners',
      'hi': 'बिजली और आकाश का स्वामी',
    },
    'M11': {
      'ko': '대양의 파도를 가르는 바다신',
      'en': 'Master of Ocean Waves & Tridents',
      'ja': '大海の怒涛を裂く海神',
      'zh': '裂浪破涛之大洋海神',
      'de': 'Gebieter der Weltmeere',
      'hi': 'समुद्र और तूफानों का देवता',
    },
    'M12': {
      'ko': '지하의 숨은 보물을 품은 신',
      'en': 'Keeper of Subterranean Riches',
      'ja': '地下に眠る秘宝を抱く冥王',
      'zh': '掌管幽冥地藏与珍宝之冥神',
      'de': 'Herr der Verborgenen Schätze',
      'hi': 'पाताल और भूमिगत खजाने का देवता',
    },
    'M13': {
      'ko': '용기와 천둥을 부르는 전사',
      'en': 'Thunderous Champion of Valor',
      'ja': '勇気と雷鳴を呼ぶ戦士',
      'zh': '手握雷神之锤之无畏战神',
      'de': 'Krieger des Donners',
      'hi': 'बिजली और अदम्य साहस का योद्धा',
    },
    'M14': {
      'ko': '세상의 모든 지혜를 탐구하는 자',
      'en': 'Allfather of Runes & Omniscience',
      'ja': '世の全知を極めし最高神',
      'zh': '勘破卢恩符文之全知诸神之父',
      'de': 'Allvater des Wissens & der Runen',
      'hi': 'समस्त ज्ञान और रून का जनक',
    },
    'M15': {
      'ko': '정의로운 전략과 지혜의 여신',
      'en': 'Goddess of Strategic Insight & Wisdom',
      'ja': '正義の戦略と知恵の女神',
      'zh': '正义谋略与智慧女神',
      'de': 'Göttin der Weisheit & Strategie',
      'hi': 'बुद्धि और सटीक रणनीति की देवी',
    },
    'M16': {
      'ko': '태양과 예술의 빛을 비추는 신',
      'en': 'Luminary of Sun & Artistry',
      'ja': '太陽と芸術の光を灯す神',
      'zh': '照耀阳光与诗意艺术之神',
      'de': 'Lichtbringer der Kunst & Sonne',
      'hi': 'सूर्य और कला का तेजस्वी देवता',
    },
    'M17': {
      'ko': '유쾌한 반전을 선사하는 장난꾸러기',
      'en': 'Trickster of Delightful Twists',
      'ja': '痛快な逆転劇を呼ぶ悪戯神',
      'zh': '妙趣横生巧妙破局之神',
      'de': 'Schalk der Überraschenden Wendungen',
      'hi': 'चतुर और अप्रत्याशित मोड़ों का देवता',
    },
    'M18': {
      'ko': '승리의 깃발을 든 하늘의 메신저',
      'en': 'Winged Herald of Victory',
      'ja': '勝利の旗印を掲げる飛翔の使者',
      'zh': '高擎胜利战旗之御风女武神',
      'de': 'Geflügelte Botin des Sieges',
      'hi': 'जीत का ध्वज लहराने वाली वीरांगना',
    },
    'M19': {
      'ko': '영원한 평온과 자비의 깨달음',
      'en': 'Awakened One of Boundless Compassion',
      'ja': '永遠の平穏と慈悲の悟り',
      'zh': '永恒宁静大慈大悲之觉者',
      'de': 'Erleuchteter Zeitlosen Friedens',
      'hi': 'परम शांति और करुणा के बुद्ध',
    },
    'M20': {
      'ko': '세상의 소리를 듣는 대자대비',
      'en': 'All-Hearing Sovereign of Mercy',
      'ja': '世の音を聞き届ける大慈大悲',
      'zh': '寻声救苦大慈大悲之观世音',
      'de': 'Allerbarmende Mutter der Gnade',
      'hi': 'संसार की पुकार सुनने वाली दया की देवी',
    },
    'M21': {
      'ko': '모든 장애를 허무는 복의 신',
      'en': 'Overcomer of Every Obstacle',
      'ja': '百難を砕く福徳の神',
      'zh': '踏碎一切阻障之吉祥福神',
      'de': 'Beseitiger Aller Hindernisse',
      'hi': 'विघ्नहर्ता मंगलकारी गणेश',
    },
    'M22': {
      'ko': '변혁과 생명의 춤추는 군주',
      'en': 'Cosmic Dancer of Rebirth',
      'ja': '変革と生命を踊る舞踏の覇王',
      'zh': '舞动造化与重生之大自在天',
      'de': 'Kosmischer Tänzer der Erneuerung',
      'hi': 'नटराज भगवान शिव',
    },
    'M23': {
      'ko': '동방의 하늘을 호령하는 제석천',
      'en': 'Thunder Lord of Eastern Skies',
      'ja': '東方の天空を号令する帝釈天',
      'zh': '威震东方天界之天帝因陀罗',
      'de': 'Donnergott der Östlichen Himmel',
      'hi': 'स्वर्ग के राजा इंद्रदेव',
    },
    'M24': {
      'ko': '온 세상을 비추는 태양의 매',
      'en': 'Solar Falcon of the Universe',
      'ja': '万物を照らす太陽のハヤブサ',
      'zh': '普照大千之曜阳猎鹰',
      'de': 'Sonnengott des Kosmos',
      'hi': 'समस्त ब्रह्मांड को चमकाने वाले सूर्य',
    },
    'M25': {
      'ko': '부활과 생명을 싹틔우는 군주',
      'en': 'Sovereign of Resurrection & Crops',
      'ja': '復活と生命の芽吹きを司る王',
      'zh': '执掌复苏与丰沃之冥府法王',
      'de': 'König der Wiederauferstehung',
      'hi': 'पुनर्जन्म और समृद्धि का शासक',
    },
    'M26': {
      'ko': '기쁨과 평화를 수호하는 묘신',
      'en': 'Feline Goddess of Joy & Hearth',
      'ja': '喜びと安らぎを守護する猫神',
      'zh': '司掌喜乐与守护家宅之猫女神',
      'de': 'Schützerin von Freude & Heim',
      'hi': 'आनंद और घर की रक्षक बिल्ली देवी',
    },
    'M27': {
      'ko': '진실의 무게를 재는 인도관',
      'en': 'Weigher of Truth & Souls',
      'ja': '真実の重さを量る導師',
      'zh': '权衡心灵羽毛之冥途引路者',
      'de': 'Wäger der Seelen & Wahrheit',
      'hi': 'सच्चाई और कर्म को तौलने वाला देवता',
    },
    'M28': {
      'ko': '어둠을 가르는 수호의 등불',
      'en': 'Champion of Light & Defense',
      'ja': '闇を切り裂く守護の灯火',
      'zh': '荡涤暗夜之光明斩邪战帅',
      'de': 'Streiter des Lichts & Beschützer',
      'hi': 'अंधकार को चीरने वाले प्रकाश के रक्षक',
    },
    'M29': {
      'ko': '기쁜 소식을 전하는 희망의 전령',
      'en': 'Herald of Glad Tidings & Hope',
      'ja': '吉報を告げる希望の使徒',
      'zh': '吹响救恩号角之喜报天使',
      'de': 'Überbringer Froher Botschaft',
      'hi': 'शुभ समाचार और आशा के दूत',
    },
    'M30': {
      'ko': '지친 여정을 보듬는 치유의 손길',
      'en': 'Gentle Physician of Travelers',
      'ja': '旅路を抱きとめる癒しの御手',
      'zh': '抚平旅途创伤之仁慈医者',
      'de': 'Heiler der Verwundeten',
      'hi': 'थके हुए यात्रियों को चंगा करने वाले दूत',
    },
    'M31': {
      'ko': '어둠을 사르는 지혜의 등대',
      'en': 'Beacon Illuminating the Void',
      'ja': '闇を焦がす知恵の灯台',
      'zh': '照破歧路迷津之真理明灯',
      'de': 'Leuchtfeuer der Wahrheit',
      'hi': 'अंधकार में ज्ञान की मशाल',
    },
    'M32': {
      'ko': '한순간도 떠나지 않는 다정한 그림자',
      'en': 'Ever-Present Shadow of Love',
      'ja': '一瞬たりとも離れぬ優しき影',
      'zh': '朝夕相伴寸步不离之温柔庇佑',
      'de': 'Treuer Begleiter des Lebens',
      'hi': 'हर पल साथ रहने वाली दयालु छाया',
    },
    'M33': {
      'ko': '아름다운 운명의 실을 잣는 여신',
      'en': 'Weavers of Golden Destiny',
      'ja': '美しき運命の糸を紡ぐ女神',
      'zh': '纺织金色天命之丝之命运三女神',
      'de': 'Weberinnen des Goldenen Fadens',
      'hi': 'भाग्य का सुंदर धागा बुनने वाली देवियां',
    },
  };

  static const Map<String, Map<String, String>> descs = {
    'Z01': {
      'ko': '어둠 속에서도 길을 찾아내고, 부의 황금 열쇠를 물어다 주는 아주 영특한 기운입니다.',
      'en': 'Finds a path even in darkness and brings the golden key of wealth with clever insight.',
      'ja': '暗闇の中でも道を見出し、富の黄金の鍵を運んでくる賢明な気運です。',
      'zh': '在黑暗中亦能洞见前路，以无上聪慧衔来开启财富之门的黄金钥匙。',
      'de': 'Findet selbst in tiefster Dunkelheit den Pfad und bringt den goldenen Schlüssel des Reichtums.',
      'hi': 'अंधेरे में भी मार्ग खोज निकालता है और अपार बुद्धि से धन की स्वर्ण कुंजी लाता है।',
    },
    'Z02': {
      'ko': '한 걸음 한 걸음 우직하게 나아가 마침내 큰 결실을 맺게 돕는 든든한 황소의 힘입니다.',
      'en': 'Steps steadily forward one pace at a time, bringing great harvest with the reliable power of the ox.',
      'ja': '一歩一歩着実に歩み、ついに大きな実りを結ばせる頼もしい雄牛の力です。',
      'zh': '脚踏实地步步向前，以坚实沉稳的耕牛之力助您结出丰硕成果。',
      'de': 'Schreitet Schritt für Schritt beständig voran und bringt mit der Kraft des Stiers reiche Ernte.',
      'hi': 'एक-एक कदम दृढ़ता से आगे बढ़ाता है और बैल की अटूट शक्ति से महान सफलता दिलाता है।',
    },
    'Z03': {
      'ko': '매서운 눈빛으로 나쁜 액운을 단칼에 베어 넘기고, 집안에 대운의 문을 활짝 열어 줍니다.',
      'en': 'Cuts down misfortune with a fierce gaze and opens wide the gates of fortune for your home.',
      'ja': '鋭い眼光で厄災を一刀両断し、家に大運の扉を大きく開きます。',
      'zh': '以凛冽威严的目光斩断厄运，为门第敞开迎纳鸿运的浩荡大门。',
      'de': 'Vertreibt Unheil mit kühnem Blick und öffnet weit die Pforten des großen Glücks.',
      'hi': 'तीक्ष्ण दृष्टि से सभी अनिष्टों को काट फेंकता है और घर में अपार सौभाग्य के द्वार खोलता है।',
    },
    'Z04': {
      'ko': '달빛 아래서 번뜩이는 영감을 빚어내어, 위기를 껑충 뛰어넘는 지혜를 선물합니다.',
      'en': 'Crafts brilliant inspiration beneath the moonlight, granting wisdom to leap over crises.',
      'ja': '月光の下で輝くインスピレーションを紡ぎ、危機を飛び越える知恵を授けます。',
      'zh': '在月光之下孕育闪耀灵感，赐予轻盈跃过险阻危机的超然智慧。',
      'de': 'Formt Inspiration im Mondlicht und schenkt die Klugheit, Hindernisse leicht zu überspringen.',
      'hi': 'चांदनी में चमकती प्रेरणा रचता है और संकटों से पार पाने का चतुर ज्ञान देता है।',
    },
    'Z05': {
      'ko': '사슴 뿔과 푸른 여의주를 품에 안고 승천하는 아기 청룡처럼, 하늘과 땅의 조화로운 대운을 열어 줍니다.',
      'en': 'Ascending with deer antlers and an azure jewel, it unlocks harmonious destiny across heaven and earth.',
      'ja': '鹿の角と青き如意宝珠を抱き昇天する青龍の如く、天地の調和なる大運を開きます。',
      'zh': '怀抱苍翠龙珠腾霄而起，为天地之间开启万物调和、福运昌隆之壮景。',
      'de': 'Steigt mit Hirschgeweih und blauem Juwel empor und entfaltet harmonisches Glück zwischen Himmel und Erde.',
      'hi': 'नीली मणि लेकर आकाश में उड़ता है और स्वर्ग व पृथ्वी के बीच असीम सद्भाव लाता है।',
    },
    'Z06': {
      'ko': '허물을 벗고 새롭게 거듭나듯, 깊은 직관과 통찰력으로 인생의 중요한 전환점을 이끌어준다.',
      'en': 'Like shedding old skin for rebirth, guides major turning points with deep intuition.',
      'ja': '脱皮して新たに生まれ変わるように、鋭い直感と洞察力で人生の転機を導きます。',
      'zh': '如蜕皮新生般脱胎换骨，凭借深刻的直觉与洞察力指引人生的关键转折。',
      'de': 'Streift das Alte ab wie eine Häutung und führt mit tiefer Intuition zu Neuanfängen.',
      'hi': 'पुरानी केंचुली छोड़ नया जन्म लेने की तरह, यह जीवन के मोड़ों पर सही मार्गदर्शन करता है।',
    },
    'Z07': {
      'ko': '푸른 갈기를 휘날리며 거침없이 대지를 질주하듯, 목표를 향해 힘차게 뻗어나가는 기운을 북돋아 줍니다.',
      'en': 'Gallops fearlessly across the land, invigorating your spirit to surge toward your goals.',
      'ja': 'たてがみを靡かせ大地を疾走するように、目標へ力強く突き進む気運を高めます。',
      'zh': '鬃毛飞扬驰骋辽阔原野，激发您向着宏伟目标一往无前、势不可挡的磅礴意气。',
      'de': 'Galoppiert furchtlos über das Land und beflügelt die Kraft, jedes Ziel kühn zu erreichen.',
      'hi': 'हवा में अयाल लहराते हुए दौड़ता है और आपके लक्ष्यों की ओर असीम ऊर्जा भर देता है।',
    },
    'Z08': {
      'ko': '포근하고 순백의 털처럼 주변 사람들과의 관계를 부드럽게 감싸고, 마음에 깊은 평안을 가져다줍니다.',
      'en': 'Warm like soft white fleece, gently harmonizes relationships and brings deep inner serenity.',
      'ja': '温かく純白な毛のように人々との縁を優しく包み込み、心に深い安らぎをもたらします。',
      'zh': '如温软纯净的白毛般轻柔包裹人际关系，为心灵带来深远祥和的宁静庇佑。',
      'de': 'Hüllt Beziehungen sanft in Wärme und schenkt dem Geist tiefe innere Stille.',
      'hi': 'सफेद ऊन की तरह रिश्तों को सौम्य बनाता है और मन को गहरी शांति प्रदान करता है।',
    },
    'Z09': {
      'ko': '나무를 자유롭게 넘나드는 영특함으로, 어떤 난관도 유쾌한 아이디어로 돌파하게 돕습니다.',
      'en': 'Leaps freely among treetops, helping you overcome obstacles with clever, joyful ideas.',
      'ja': '木々を自由に行き交う聡明さで、どんな難局も愉快な発想で突破できるよう助けます。',
      'zh': '穿梭树梢般的超然机敏，助您以巧妙欢畅的绝妙创意化解一切重重险阻。',
      'de': 'Springt behände durch Wipfel und hilft, jede Hürde mit geistreichen Ideen zu nehmen.',
      'hi': 'पेड़ों पर निपुणता से कूदता है और किसी भी बाधा को बुद्धिमान विचारों से सुलझा देता है।',
    },
    'Z10': {
      'ko': '어둠을 가르고 아침의 첫 빛을 알리듯, 새로운 기회와 번영의 시작을 알차게 깨워 줍니다.',
      'en': 'Breaks through shadow to herald the morning light, awakening new opportunities and prosperity.',
      'ja': '闇を裂き朝の光を告げるように、新たな好機と繁栄の始まりを清らかに目覚めさせます。',
      'zh': '啼鸣破晓引来天地初光，精准唤醒崭新机遇与繁华昌盛的璀璨开端。',
      'de': 'Durchbricht das Dunkel mit dem ersten Sonnenstrahl und weckt frische Chancen und Erfolg.',
      'hi': 'अंधकार चीरकर सुबह की पहली किरण लाता है और नए अवसरों व समृद्धि का आरंभ करता है।',
    },
    'Z11': {
      'ko': '언제나 한결같은 충성심으로 소중한 인연과 재산을 단단히 지켜내어 안심을 주는 든든한 벗입니다.',
      'en': 'Guards cherished bonds and treasures with unwavering loyalty, giving reassuring peace of mind.',
      'ja': '変わらぬ忠誠心で大切な縁と財産を堅く守り抜き、安心をもたらす心強い友です。',
      'zh': '以始终不渝的忠贞之志坚守珍贵因缘与家产，带来无限安然与踏实依靠。',
      'de': 'Beschützt Bande und Güter mit unerschütterlicher Treue und schenkt beruhigende Geborgenheit.',
      'hi': 'अटूट वफादारी से अपनों और संपत्ति की रक्षा करता है और मन को गहरा विश्वास देता है।',
    },
    'Z12': {
      'ko': '황금빛 복을 가득 품고 집안에 부와 번영을 넉넉하게 쏟아부어주는 만복의 상징입니다.',
      'en': 'Laden with golden fortune, pours overflowing wealth and prosperity into your household.',
      'ja': '黄金の福を豊かに宿し、家に富と繁栄を惜しみなく注ぎ込む万福の象徴です。',
      'zh': '满载璀璨金光福瑞，为门庭源源倾注财帛繁荣，乃万福骈臻之上吉之兆。',
      'de': 'Voll goldenem Segen ergießt es Reichtum und Gedeihen in Hülle und Fülle über das Haus.',
      'hi': 'सोने जैसे आशीर्वाद से परिपूर्ण, घर में धन-दौलत और समृद्धि की वर्षा करता है।',
    },
    'Z13': {
      'ko': '시비곡직을 올바르게 판단하고 화재와 재앙을 물리치는 상서로운 신수입니다.',
      'en': 'Discerning right from wrong, wards off fire and calamity as an auspicious guardian beast.',
      'ja': '是非曲直を正しく裁き、火災と災厄を退ける瑞祥の神獣です。',
      'zh': '辨曲直定是非，能镇灾辟火涤荡邪佞，庇佑四方之祥瑞神兽。',
      'de': 'Urteilt gerecht zwischen Recht und Unrecht und wendet Feuer und Unheil verlässlich ab.',
      'hi': 'सही और गलत का निष्पक्ष न्याय करता है और आग व संकटों को दूर भगाता है।',
    },
    'Z14': {
      'ko': '자비롭고 어진 성인의 출현과 세상의 평화로운 번영을 축복하는 신수입니다.',
      'en': 'Blesses the world with peace and prosperous harmony upon the advent of benevolent wisdom.',
      'ja': '慈悲深き聖人の出現と、世の平和なる繁栄を祝福する神獣です。',
      'zh': '见证仁爱圣贤出世，普惠世间天下太平、家肥屋润之至圣祥兽。',
      'de': 'Kündet vom Aufstieg weiser Seelen und segnet das Land mit Frieden und Blüte.',
      'hi': 'महान पुरुषों के आगमन और दुनिया में शांति व खुशहाली का आशीर्वाद देता है।',
    },
    'Z15': {
      'ko': '붉은 불꽃의 날갯짓으로 사악한 기운을 태우고 불굴의 생명력을 불어넣습니다.',
      'en': 'Flaps wings of crimson flame to incinerate evil energy and breathe unyielding life.',
      'ja': '紅蓮の炎の羽ばたきで邪気を焼き払い、不屈の生命力を吹き込みます。',
      'zh': '展赤焰之翼焚尽幽晦邪气，为万物注入生生不息、坚忍不拔的蓬勃生机。',
      'de': 'Verbrennt dunkle Mächte mit purpurnen Flammen und entfacht unbezwingbaren Lebensmut.',
      'hi': 'लाल अग्नि के पंख फड़फड़ाकर बुराई को भस्म करता है और अटूट जीवनशक्ति भरता है।',
    },
    'Z16': {
      'ko': '뱀과 거북이 하나 되어 영겁의 세월 동안 건강과 굳건한 터전을 지켜준다.',
      'en': 'Entwined serpent and tortoise protect your health and steadfast foundation through eternity.',
      'ja': '亀と蛇が一体となり、永劫の歳月にわたり健康と揺るぎなき基盤を守護します。',
      'zh': '龟蛇相合融汇万劫岁月，永世镇守安康体魄与坚如磐石之恒久基业。',
      'de': 'Schildkröte und Schlange vereint wahren Gesundheit und Fundamente für alle Zeit.',
      'hi': 'कछुआ और सांप मिलकर अनंत काल तक उत्तम स्वास्थ्य और दृढ़ नींव की रक्षा करते हैं।',
    },
    'Z17': {
      'ko': '깊은 영산에서 맑은 이슬을 먹고 자라 순수한 치유와 무병장수의 기운을 건넵니다.',
      'en': 'Nourished by pure dew upon sacred peaks, delivers healing grace and illness-free vitality.',
      'ja': '深き霊山で清らかな露を食み、純粋なる治癒と無病息災の気運を授けます。',
      'zh': '饮灵山甘露而生，赐予人世纯净无瑕的治愈力量与福寿绵长的长生灵韵。',
      'de': 'Nährt sich vom Tau der Berge und schenkt reine Heilung und zeitlose Gesundheit.',
      'hi': 'पवित्र पहाड़ों की ओस पीकर जीता है और शुद्ध उपचार व दीर्घायु का वरदान देता है।',
    },
    'Z18': {
      'ko': '오색 깃털을 빛내며 가장 고귀하고 덕망 높은 복을 집안 가득 선물합니다.',
      'en': 'Radiates five-colored feathers, filling homes with nobility, virtue, and peerless blessings.',
      'ja': '五色の羽を輝かせ、この上なく気高く徳高き福徳を家いっぱいに届けます。',
      'zh': '五彩霞光流转生辉，将世间至尊至贵、德厚流光之福报倾注于宅第之中。',
      'de': 'Strahlt in fünf Farben und erfüllt das Haus mit erhabenstem Glück und Ansehen.',
      'hi': 'पंचरंगी पंखों से चमकता है और घर में सबसे ऊंचा सम्मान व सौभाग्य भरता है।',
    },
    'Z19': {
      'ko': '천상의 빛을 이 땅에 전하며 하늘과 땅의 뜻을 잇는 위대한 광명의 사자입니다.',
      'en': 'Conveys celestial radiance to earth, bridging the will of heaven and humanity with glorious light.',
      'ja': '天上の光を地上へと届け、天と地の意思を繋ぐ大いなる光明の使者です。',
      'zh': '将九天极光播撒人间，承接日月之志，乃沟通天地浩然光明之神圣使者。',
      'de': 'Überbringt himmlischen Glanz und verbindet die Welten mit leuchtender Sonnenkraft.',
      'hi': 'स्वर्ग के प्रकाश को धरती पर लाता है और आकाश व पृथ्वी के बीच सेतु बनता है।',
    },
    'Z20': {
      'ko': '아홉 개의 꼬리마다 신통한 도술과 사람의 마음을 끄는 매혹의 지혜를 담고 있습니다.',
      'en': 'Each of nine tails holds mystical arts and charming wisdom that attracts hearts and good allies.',
      'ja': '九つの尾それぞれに霊妙なる術と、人の心を惹きつける魅惑の知恵を宿しています。',
      'zh': '九尾各自吞吐玄妙神通，蕴含摄人心魄、巧解万事之通天智慧与魅力。',
      'de': 'Jeder der neun Schweife birgt magische Künste und bezwingende Klugheit.',
      'hi': 'इसकी नौ पूंछों में चमत्कारी विद्या और दिलों को जीतने वाली बुद्धि समाई है।',
    },
    'Z21': {
      'ko': '영롱한 외뿔의 빛으로 상처 입은 마음을 어루만지고 기적 같은 행운을 부릅니다.',
      'en': 'Soothes wounded hearts with the pristine glow of its horn, summoning miraculous fortune.',
      'ja': '玲瓏たる一角の光で傷ついた心を癒し、奇跡のような幸運を呼び寄せます。',
      'zh': '以晶莹独角之灵辉抚慰创伤，唤来宛如神迹降临般的绝处逢生之大幸。',
      'de': 'Heilt verletzte Herzen im Schimmer seines Horns und ruft wundersames Glück herbei.',
      'hi': 'अपने सींग के दिव्य प्रकाश से दुखों को मिटाता है और चमत्कारिक भाग्य जगाता है।',
    },
    'Z22': {
      'ko': '이마의 제3의 눈으로 숨은 액운까지 낱낱이 찾아내어 쫓아내는 영험한 수호견이다.',
      'en': 'Uncovers and banishes even concealed misfortunes with the mystical third eye upon its brow.',
      'ja': '額の第三の眼で潜む不運すら見破り、追い払う霊験あらたかな守護犬です。',
      'zh': '以天庭第三只法眼彻查隐匿祸患并彻底祓除，威灵显赫的忠勇护法灵犬。',
      'de': 'Spürt mit dem dritten Auge selbst verborgenes Unheil auf und jagt es in die Flucht.',
      'hi': 'माथे की तीसरी आंख से छुपे हुए संकटों को ढूंढकर हमेशा के लिए भगा देता है।',
    },
    'Z23': {
      'ko': '모든 길 앞을 가로막는 장애물을 걷어내고 부귀영화를 안겨주는 지혜의 신수입니다.',
      'en': 'Removes all barriers across your path, ushering in wisdom, abundance, and auspicious starts.',
      'ja': '行く手を塞ぐ障害を取り払い、富貴栄華をもたらす知恵の霊神です。',
      'zh': '扫除前路一切艰难险阻，赐予金玉满堂、万事胜意之超凡福泽。',
      'de': 'Beseitigt alle Hindernisse auf Ihrem Lebensweg und gewährt Reichtum und Einsicht.',
      'hi': 'रास्ते की सभी बाधाओं को दूर करता है और ज्ञान, समृद्धि व नए आरंभ का आशीर्वाद देता है।',
    },
    'Z24': {
      'ko': '마르지 않는 강물의 축복으로 비옥한 땅과 마르지 않는 재물을 선사합니다.',
      'en': 'Bestows fertile grounds and ceaseless wealth through the blessings of unyielding rivers.',
      'ja': '尽きることなき大河の祝福により、豊かな大地と枯れぬ財を授けます。',
      'zh': '以源源不断的圣河活水浇灌丰饶沃野，赋予永不枯竭的充盈资财。',
      'de': 'Schenkt fruchtbaren Boden und unversiegbaren Wohlstand durch den Strom des Lebens.',
      'hi': 'सदा बहती नदियों के आशीर्वाद से उपजाऊ भूमि और कभी न खत्म होने वाला धन देता है।',
    },
    'Z25': {
      'ko': '천 년의 수련 끝에 여의주를 품고 마침내 용으로 비상하는 끈기와 대성의 기운입니다.',
      'en': 'Embraces the wishing orb after a millennium of discipline, soaring into a full dragon of triumph.',
      'ja': '千年の修行を経て如意宝珠を抱き、ついに龍となり飛翔する不屈と大成の気運です。',
      'zh': '千载潜修终衔如意宝珠化龙腾飞，蕴藏百折不挠、大器晚成之冲天浩气。',
      'de': 'Erreicht nach tausend Jahren Ausdauer die Drachengestalt und triumphiert über alle Grenzen.',
      'hi': 'कठिन तपस्या के बाद चमत्कारी मणि पाकर उड़ता है और धैर्य से सफलता दिलाता है।',
    },
    'Z26': {
      'ko': '거센 폭포를 거슬러 올라 큰 성공과 입신양명의 기적을 이루어낸다.',
      'en': 'Leaps upstream through raging waterfalls, achieving glorious triumph and social acclaim.',
      'ja': '荒波の滝を遡り、立身出世と偉大なる栄達の奇跡を成し遂げます。',
      'zh': '溯狂澜逆流而上越过天门，缔造金榜题名、一举成名天下知之绝顶奇迹。',
      'de': 'Überwindet reißende Wasserfälle und erzielt ruhmreichen Erfolg und gesellschaftliche Ehre.',
      'hi': 'तेज लहरों को चीरकर ऊपर चढ़ता है और असाधारण सफलता व यश प्राप्त कराता है।',
    },
    'Z27': {
      'ko': '지혜로운 문답을 통해 감추어진 황금 보물 창고의 문을 열어 줍니다.',
      'en': 'Unlocks hidden golden chambers for those who answer its profound riddles of wisdom.',
      'ja': '賢明なる対話を通じて、隠された黄金の宝物庫の扉を開き放ちます。',
      'zh': '在智慧的问答辩证中，为通达之人开启沉睡千载的秘藏黄金宝库大门。',
      'de': 'Öffnet verborgene Schatzkammern für jene, die seine weisen Rätsel ergründen.',
      'hi': 'ज्ञान भरी पहेलियों के सही उत्तर पाकर छुपे हुए स्वर्ण खजाने के द्वार खोल देता है।',
    },
    'Z28': {
      'ko': '심해의 무한한 자원과 잠재력을 깨워 거대한 포용력과 활력을 선물합니다.',
      'en': 'Awakens the infinite potential of the abyss, granting immense tolerance and vital energy.',
      'ja': '深海の無尽蔵な資源と潜在力を呼び覚まし、大いなる包容力と活力を授けます。',
      'zh': '唤醒深邃大洋的无尽潜能，赋予海纳百川之博大胸怀与源源不断的生命活力。',
      'de': 'Erweckt unendliche Tiefenkräfte und verleiht weite Großmut und vitale Stärke.',
      'hi': 'समुद्र के असीम सामर्थ्य को जगाता है और गहरी सहनशीलता व प्रचंड ऊर्जा देता है।',
    },
    'Z29': {
      'ko': '예리한 감각으로 집안에 숨어든 나쁜 기운을 물리치고 편안한 잠자리를 지켜 냅니다.',
      'en': 'Banishes subtle negative energies with keen senses, securing sound slumber and peace.',
      'ja': '鋭い感覚で家に入り込む邪気を退け、心安らぐ安眠を守り抜きます。',
      'zh': '凭敏锐感官洞察并驱散暗伏之晦气，全心护佑阖家安枕无忧、美梦酣甜。',
      'de': 'Wittert verborgene Dunkelheit und bewahrt ruhigen Schlaf und inneren Frieden.',
      'hi': 'अपनी तीखी सूझबूझ से घर की नकारात्मकता दूर करता है और सुखद नींद की रक्षा करता है।',
    },
    'Z30': {
      'ko': '세 발로 온 세상의 재물을 끌어모아 금고 가득 채워주는 복두꺼비입니다.',
      'en': 'Gathers riches across the realm with its three feet, packing your vault with gold.',
      'ja': '三本足で世界中の財宝をかき集め、金庫を満杯にする福徳のヒキガエルです。',
      'zh': '以三足跳跃招揽天下八方财宝，金银财帛源源不绝盈满金匮之纳财灵物。',
      'de': 'Rafft Reichtümer der Welt herbei und füllt Schatzkammern bis zum Rand.',
      'hi': 'तीनों पैरों से दुनिया भर की दौलत बटोरता है और तिजोरियों को धन से भर देता है।',
    },
    'Z31': {
      'ko': '독수리의 날개와 사자의 힘으로 값진 보물과 명예를 철통같이 지켜낸다.',
      'en': 'Defends priceless treasures and honors ironclad with eagle wings and lion might.',
      'ja': '鷲の翼と獅子の剛力で、貴き宝物と名誉を鉄壁の如く守り抜きます。',
      'zh': '融合苍鹰双翼与雄狮伟力，固若金汤地护卫弥足珍贵之宝藏与无上荣耀。',
      'de': 'Wacht mit Adlerflügeln und Löwenmut eisern über Reichtum, Ehre und Tugend.',
      'hi': 'चील के पंखों और शेर के बल से अनमोल खजाने व सम्मान की अटूट रक्षा करता है।',
    },
    'Z32': {
      'ko': '어떤 시련이 닥쳐도 다시 타오르는 불꽃처럼 찬란한 재기와 성공을 보장한다.',
      'en': 'Ensures brilliant resurgence and triumph like flames reborn, no matter the hardship.',
      'ja': 'いかなる試練に遭おうとも再び燃え盛る炎の如く、輝かしい再起と大成を約束します。',
      'zh': '纵遭千难万险亦如炽焰破茧重生，昭示柳暗花明之辉煌再起与宏阔功成。',
      'de': 'Verheißt nach jeder Prüfung strahlenden Wiederaufstieg wie eine Flamme aus Asche.',
      'hi': 'हर संकट के बाद आग की तरह फिर उठ खड़ा होता है और शानदार जीत सुनिश्चित करता है।',
    },
    'Z33': {
      'ko': '무지개 깃털로 하늘을 날며 새로운 지식과 풍요로운 문명의 씨앗을 뿌려 줍니다.',
      'en': 'Soars through skies with rainbow plumes, sowing seeds of innovation, wisdom, and culture.',
      'ja': '虹色の羽毛で天を翔け、新しき英知と豊かな文明の種を蒔いてくれます。',
      'zh': '披拂七彩绚羽飞跃苍穹，为大地播撒开拓创新之知识与文明繁华的硕果。',
      'de': 'Gleitet mit Regenbogenfedern durch die Lüfte und sät Samen von Einsicht und Kultur.',
      'hi': 'इंद्रधनुषी पंखों से उड़कर नए ज्ञान, आविष्कार और समृद्धि के बीज बोता है।',
    },
    'M01': {
      'ko': '영산의 맑은 정기를 품고 산천을 굽어보며, 길을 잃은 이에게 자애로운 가호와 영험한 지혜를 내려 줍니다.',
      'en': 'Gazing over peaks with pure spirit, blesses lost wanderers with caring protection and divine wisdom.',
      'ja': '霊山の澄んだ精気を宿し山河を見守り、道に迷う者に慈愛の加護と霊妙な知恵を授けます。',
      'zh': '吞吐灵山苍翠浩气俯瞰群川，为迷途求索之人降下慈悲护佑与通达法智。',
      'de': 'Blickt mit reinem Geist über heilige Höhen und schenkt Schutz und weisen Rat.',
      'hi': 'पवित्र पहाड़ों से सबको देखता है और भटके हुए लोगों को कृपा व दिव्य ज्ञान प्रदान करता है।',
    },
    'M02': {
      'ko': '운명과 인연의 길을 인도하는 길잡이로서, 악한 액운을 끊어내고 바른 길로 나아갈 수 있도록 이끌어 줍니다.',
      'en': 'As guide of karma and destiny, severs malevolent hexes and leads you along the righteous path.',
      'ja': '運命と因縁の導き手として、悪しき厄運を断ち切り正しい道へと進めるよう導きます。',
      'zh': '明辨因果掌司命途，替您斩断纠缠晦厄，引领灵犀迈向光明端正之坦途。',
      'de': 'Trennt böse Bande und leitet die Seele sicher auf den Pfad der Wahrheit und Gerechtigkeit.',
      'hi': 'भाग्य का मार्गदर्शक बनकर बुरे प्रभावों को काटता है और सही मार्ग दिखाता है।',
    },
    'M03': {
      'ko': '천상계의 질서와 조화를 다스리는 최고 천제로서, 온 세상의 균형을 맞추고 큰 대운을 베풀어 줍니다.',
      'en': 'Governs cosmic order as sovereign of the heavens, balancing the realm and bestowing grand destinies.',
      'ja': '天界の秩序と調和を司る最高位の天帝として、世の均衡を保ち大いなる運命を授けます。',
      'zh': '掌管三界至高法度与诸天秩序，权衡万物纲纪，为有德之人降下浩瀚鸿福。',
      'de': 'Regiert die himmlische Ordnung, stiftet kosmische Balance und verleiht großes Schicksal.',
      'hi': 'ब्रह्मांडीय व्यवस्था का संचालन करता है और संसार में संतुलन बनाकर परम सौभाग्य देता है।',
    },
    'M04': {
      'ko': '명경대로 진실을 비추는 공평무사한 심판관으로서, 정의를 바로 세우고 억울함을 씻어내 줍니다.',
      'en': 'Reflecting truth in the mirror of karma, upholds righteousness and washes away all grievances.',
      'ja': '浄玻璃の鏡で真実を映し出す審判官として、正義を正し無念の思いを晴らしてくれます。',
      'zh': '以业镜映照因果真伪，秉公断狱立柱天地正气，为受屈之人昭雪沉冤。',
      'de': 'Enthüllt die Wahrheit im Spiegel der Taten, stellt Gerechtigkeit her und reinigt die Seele.',
      'hi': 'कर्म के दर्पण में सच्चाई देखता है, न्याय की स्थापना करता है और निर्दोषों को राहत देता है।',
    },
    'M05': {
      'ko': '태초의 대지와 삼라만상을 빚어낸 거신 창조주로서, 무한한 포용력과 생명력의 터전을 안겨 줍니다.',
      'en': 'Giant creator crafting mountains and earth from the dawn, offering boundless embrace and vitality.',
      'ja': '太初の大地と森羅万象を創り出した母なる巨人として、無限の包容力と生命の土台を授けます。',
      'zh': '塑天地山川与森罗万象之创世元母，以博大宽仁赐予众生生生不息之厚实根基。',
      'de': 'Formte Berge und Lande seit Anbeginn und schenkt grenzenlose Geborgenheit und Urkraft.',
      'hi': 'शुरुआत में पृथ्वी और पहाड़ों की रचना करने वाली देवी, जो असीम जीवन और सुरक्षा देती हैं।',
    },
    'M06': {
      'ko': '생명수를 길어 올려 영혼을 치유하는 자비로운 공주로서, 깊은 상처를 어루만지고 기적의 소생을 돕습니다.',
      'en': 'Draws living waters to restore weary souls, tenderly nursing wounds into miraculous rebirth.',
      'ja': '生命の水を汲み上げ魂を救う慈愛の姫として、深い傷を癒し奇跡の再生をもたらします。',
      'zh': '涉远海汲取还魂甘露之仁慈公主，轻抚凡尘深重痛楚，引渡绝处逢生之奇迹。',
      'de': 'Schöpft das Wasser des Lebens, um Seelen zu heilen und Wunder der Genesung zu wirken.',
      'hi': 'अमृत जल लाकर आत्माओं को शांत करती हैं और घावों को भरकर पुनर्जीवन देती हैं।',
    },
    'M07': {
      'ko': '새 생명의 탄생과 가정의 안녕을 점지하는 온화한 어머니의 품처럼, 따뜻한 축복을 건넵니다.',
      'en': 'Bestows warm blessings like a mother\'s embrace, nurturing birth, growth, and peaceful family hearths.',
      'ja': '新しい命の誕生と家庭の安泰を司る温かい母の懐のように、柔らかな祝福を授けます。',
      'zh': '如慈母怀抱般守护新生降临与家庭和睦，庇荫老幼无灾无难、世泽绵长。',
      'de': 'Segnet neue Leben und Familien mit mütterlicher Wärme und beständigem Frieden.',
      'hi': 'मां के आंचल जैसी ममता से नवजात शिशुओं और परिवार की खुशहाली की रक्षा करती हैं।',
    },
    'M08': {
      'ko': '사해 바다의 모든 보물과 물길을 호령하는 해신으로서, 끝없는 풍요와 귀중한 기회를 가져다줍니다.',
      'en': 'Commands ocean currents and fathomless treasures, bringing inexhaustible wealth and opportunities.',
      'ja': '四海のすべての宝と潮の流れを統べる海神として、果てなき豊かさと貴き好機をもたらします。',
      'zh': '总揽汪洋水系与水下无量珍宝，翻江弄海之间为您送上滔滔不绝之机缘与巨富。',
      'de': 'Befiehlt den Fluten und Schätzen der Meere und schenkt grenzenlose Fülle und Reichtum.',
      'hi': 'समुद्र के सभी रत्नों और लहरों का स्वामी, जो असीम समृद्धि और सुनहरे अवसर लाता है।',
    },
    'M09': {
      'ko': '터전의 안녕과 보금자리를 든든히 지켜주는 가신으로서, 집안의 평온과 재물이 흩어지지 않게 수호합니다.',
      'en': 'Guardian spirit anchoring your dwelling, preserving domestic harmony so wealth never scatters.',
      'ja': '暮らしの場と住まいを固く守る家神として、家庭の平和と財の散逸を防ぎ守護します。',
      'zh': '固守一方家宅安宁之尊神，守护阖家平安康泰，力保聚气聚财不虞散逸。',
      'de': 'Bewahrt den häuslichen Frieden und sorgt dafür, dass Wohlstand und Geborgenheit bleiben.',
      'hi': 'घर की जमीन और दीवारों की रक्षा करता है, ताकि सुख-शांति और संपत्ति बनी रहे।',
    },
    'M10': {
      'ko': '천공의 벼락과 별빛을 다스리는 주신으로서, 강력한 통솔력과 당당한 승리의 위엄을 선사합니다.',
      'en': 'Wields celestial lightning and skies, bestowing commanding leadership and triumphant glory.',
      'ja': '天空の雷光と星々を司る主神として、強大な統솔力と堂々たる勝利の威厳を授けます。',
      'zh': '掌管雷霆万钧与苍穹星汉，赋予势如破竹之强大领袖气质与傲然凯旋之荣光。',
      'de': 'Herrscht über Blitze und Himmel und verleiht überragende Führungsstärke und Sieg.',
      'hi': 'आकाशीय बिजली का संचालन करता है और नेतृत्व व विजय का गौरव प्रदान करता है।',
    },
    'M11': {
      'ko': '대양의 거친 파도를 가르는 바다의 군주로서, 막힘없는 활력과 거대한 포부를 열어 줍니다.',
      'en': 'Cleaves through roaring swells, inspiring boundless vitality and magnificent ambitions.',
      'ja': '大洋の荒波を切り開く海の覇者として、留まることなき活力と大いなる野望を開きます。',
      'zh': '手持三叉戟劈开怒海狂澜，赋予排山倒海般之磅礴活力与壮志凌云之宏图。',
      'de': 'Spaltet tosende Fluten und weckt ungebremste Vitalität und große Ambitionen.',
      'hi': 'समुद्र की लहरों को चीरता है और असीम उत्साह व महान महत्वाकांक्षाओं को जगाता है।',
    },
    'M12': {
      'ko': '지하에 숨겨진 보물과 대지의 광물을 다스리는 신으로서, 보이지 않는 깊은 곳에서 결실을 맺게 돕습니다.',
      'en': 'Commands minerals and hidden underground riches, quietly yielding fruit in secret depths.',
      'ja': '地下深くに眠る鉱物と財宝を司る神として、見えざる深き処で実りを結ぶよう導きます。',
      'zh': '统御地底万千金玉矿脉，在暗处潜心积淀，终成厚积薄发、惊艳世人之大器。',
      'de': 'Gebietet über Schätze im Erdinneren und lässt Früchte im Verborgenen reifen.',
      'hi': 'धरती के नीचे दबे खजाने का स्वामी, जो अनदेखी गहराइयों में भी सफलता दिलाता है।',
    },
    'M13': {
      'ko': '천둥의 묠니르를 휘두르는 용맹한 전사로서, 어떤 난관도 단숨에 부수고 승리를 쟁취하게 돕습니다.',
      'en': 'Wields Mjolnir with warrior courage, shattering obstacles instantly to seize triumph.',
      'ja': '雷神の鎚ミョルニルを振るう勇猛な戦士として、いかなる困難も粉砕し勝利を掴み取ります。',
      'zh': '挥舞神锤雷鸣震彻乾坤，以雷霆万钧之势荡平一切荆棘险阻，摘取大捷。',
      'de': 'Schwingt Mjölnir mit Heldenmut, zertrümmert jede Hürde und erkämpft den Sieg.',
      'hi': 'अपने शक्तिशाली हथौड़े से किसी भी मुश्किल को एक झटके में तोड़कर जीत दिलाता है।',
    },
    'M14': {
      'ko': '세상의 모든 지혜와 룬 문자를 탐구한 올파더로서, 깊은 통찰력과 지혜로운 결단을 이끌어 줍니다.',
      'en': 'Allfather who explored runes and universal wisdom, guiding deep vision and prudent resolves.',
      'ja': '森羅万象の知恵とルーン文字を究めた主神として、深遠な洞察と賢明な決断へと導きます。',
      'zh': '洞悉世间一切玄机与卢恩秘字，赐予超前之远见卓识与审时度势之英明决断。',
      'de': 'Ergründete Runen und Weisheit der Welten und leitet mit tiefer Weitsicht und Klugheit.',
      'hi': 'संसार के सभी रहस्यों का ज्ञाता, जो दूरदर्शिता और सही निर्णय लेने की क्षमता देता है।',
    },
    'M15': {
      'ko': '정의로운 지혜와 필승의 전략을 상징하는 여신으로서, 명석한 두뇌와 빈틈없는 성공을 인도합니다.',
      'en': 'Symbolizes righteous strategy and keen insight, guiding flawless preparations toward success.',
      'ja': '正しき知恵と常勝の戦略を司る女神として、明晰な頭脳と破綻なき成功を導きます。',
      'zh': '以无双智谋与必胜兵略著称，助您运筹帷幄之中，决胜千里之外，成无瑕伟业。',
      'de': 'Verkörpert kluge Strategie und führt mit scharfem Verstand zu fehlerfreiem Erfolg.',
      'hi': 'सटीक रणनीति और बुद्धिमत्ता की प्रतीक, जो हर क्षेत्र में सफलता का मार्ग दिखाती हैं।',
    },
    'M16': {
      'ko': '태양의 찬란한 광명과 예술의 영감을 비추는 신으로서, 마음에 깃든 어둠을 걷어내고 밝은 미래를 엽니다.',
      'en': 'Radiates sunny brilliance and lyrical arts, clearing dark shadows to unfold a glowing future.',
      'ja': '太陽の燦然たる光明と芸術の霊感を放ち、心の闇を払い明るい未来を照らします。',
      'zh': '普照日耀璀璨圣辉与艺术灵感，拂散心头一切阴霾，引渡光明烂漫之前程。',
      'de': 'Strahlt Licht und Musenkunst aus, vertreibt Düsternis und eröffnet eine helle Zukunft.',
      'hi': 'सूर्य के प्रकाश और कला की प्रेरणा से मन का अंधकार मिटाकर उज्ज्वल भविष्य बनाता है।',
    },
    'M17': {
      'ko': '틀에 갇히지 않는 유쾌한 반전과 기지를 선사하는 장난꾸러기로서, 막힌 상황을 번뜩이는 아이디어로 뚫어 줍니다.',
      'en': 'Delivers humorous twists and unfettered wit, piercing deadlock with unconventional genius.',
      'ja': '型にとらわれぬ痛快な逆転と機転をもたらし、停滞した局面を斬新な発想で打開します。',
      'zh': '不拘泥常规绳墨，以羚羊挂角般的奇思妙想打破僵局，上演绝地逆袭之妙局。',
      'de': 'Schenkt unkonventionelle Einfälle und löst verfahrene Lagen mit genialem Schalk.',
      'hi': 'परंपराओं से हटकर सोचने की शक्ति देता है और मुश्किल हालात को चतुराई से पलट देता है।',
    },
    'M18': {
      'ko': '승리의 깃발을 들고 하늘을 가르는 메신저로서, 용기 있는 자에게 명예와 성공의 날개를 달아 줍니다.',
      'en': 'Cleaves through skies holding banners of triumph, conferring wings of glory upon the brave.',
      'ja': '勝利の旗を手に空を翔ける使者として、勇気ある者に名誉と栄達の翼を授けます。',
      'zh': '挥洒胜利旌旗翱翔长空，为披荆斩棘之勇者插上无上荣光与赫赫战功之翼。',
      'de': 'Fliegt mit Siegesbannern durch die Lüfte und verleiht Tapferen Flügel zu Ehre und Erfolg.',
      'hi': 'विजय का परचम थामे आकाश में उड़ती है और साहसी लोगों को जीत का वरदान देती है।',
    },
    'M19': {
      'ko': '영원한 평온과 자비의 깨달음을 전하는 성자로서, 번뇌를 씻어내고 마음에 고요한 안식을 선물합니다.',
      'en': 'Imparts infinite peace and compassionate awakening, washing away anxiety into still solace.',
      'ja': '永遠の安らぎと慈悲の悟りを伝える覚者として、煩悩を洗い流し心に静寂を届けます。',
      'zh': '传扬大千世界大寂静大菩提，涤荡凡尘一切忧烦妄念，赐予心灵澄澈之极乐安详。',
      'de': 'Lehrt zeitlose Gelassenheit und Mitgefühl und schenkt dem Geist tiefe Ruhe.',
      'hi': 'संसार के दुखों को मिटाकर अंतर्मन को परम शांति और करुणा का मार्ग दिखाते हैं।',
    },
    'M20': {
      'ko': '세상 모든 중생의 아픔과 소리를 자애롭게 듣는 대자대비의 보살로서, 크나큰 구원과 평안을 베풉니다.',
      'en': 'Listens tenderly to every plea of sentient beings, granting profound deliverance and comfort.',
      'ja': '生きとし生ける者の苦しみと願いを聞き届ける慈悲の菩薩として、大いなる救済をもたらします。',
      'zh': '悲悯倾听芸芸众生一切呼求与祈愿，广开甘露法门，施予无量慈航普渡之庇佑。',
      'de': 'Erhört die Nöte aller Wesen mit Milde und spendet Erlösung und wahren Trost.',
      'hi': 'हर प्राणी के दुख और प्रार्थना को ध्यान से सुनकर मुक्ति और असीम शांति देती हैं।',
    },
    'M21': {
      'ko': '모든 장애물을 부수고 부를 부르는 지혜의 신으로서, 새로운 시작과 사업 번창의 문을 활짝 열어 줍니다.',
      'en': 'Crushes impediments and invites abundance, swinging wide the doors to prosperous ventures.',
      'ja': 'あらゆる障害を打ち破り富を呼ぶ知恵の神として、新たな出発と商売繁盛の門を開きます。',
      'zh': '摧破一切前行枷锁，广纳八方金银，为开创新篇与商贾昌盛大辟坦途。',
      'de': 'Zertrümmert Widerstände und öffnet Tore für florierenden Neuanfang und Reichtum.',
      'hi': 'सारे विघ्नों को हरकर सुख-समृद्धि लाते हैं और नए व्यापार व कार्यों में सफलता देते हैं।',
    },
    'M22': {
      'ko': '낡은 것을 허물고 새로운 생명을 잉태하는 춤의 군주로서, 강력한 변화와 창조의 원동력을 깨웁니다.',
      'en': 'Dissolves the obsolete through cosmic dance, awakening monumental powers of transformation.',
      'ja': '古きものを解体し新しき命を孕む舞踏の神として、変革と創造の原動力を覚醒させます。',
      'zh': '于毁灭中孕育万物新生，以浩荡宇宙之舞唤醒冲破桎梏、再造乾坤之原始伟力。',
      'de': 'Löst Veraltetes auf und entfesselt durch kosmischen Tanz neue Schöpfungskraft.',
      'hi': 'पुराने बंधनों को मिटाकर नए जीवन का सृजन करते हैं और परिवर्तन की शक्ति जगाते हैं।',
    },
    'M23': {
      'ko': '동방의 하늘과 번개를 호령하는 제석천으로서, 당당한 기상과 드높은 명예를 지켜 줍니다.',
      'en': 'Commands lightning over oriental skies, preserving righteous dignity and elevated renown.',
      'ja': '東方の天空と雷を統べる帝釈天として、堂々たる気概と高き誉れを守護します。',
      'zh': '掌执金刚杵号令雷暴，庇佑浩然正气不坠，捍卫威加海内之卓然盛誉。',
      'de': 'Herrscht über Blitz und Himmel und schützt aufrechten Mut und hohes Ansehen.',
      'hi': 'बिजली और वर्षा के स्वामी, जो सम्मान, साहस और प्रतिष्ठा की रक्षा करते हैं।',
    },
    'M24': {
      'ko': '온 세상을 골고루 비추는 태양의 매로서, 최고의 광명과 결코 식지 않는 활력을 불어넣습니다.',
      'en': 'Golden solar falcon bathing the earth in warmth, instilling peerless light and tireless vigor.',
      'ja': '世界を遍く照らす太陽の霊鳥として、至高の光明と尽きせぬ活力を吹き込みます。',
      'zh': '化身金乌神隼普照尘寰，赐予照彻幽微之至尊华光与永不熄灭之旺盛精力。',
      'de': 'Bade die Erde in Licht und schenkt höchste Strahlkraft und unermüdlichen Elan.',
      'hi': 'धरती को अपनी किरणों से आलोकित करते हैं और कभी न थकने वाली ऊर्जा भरते हैं।',
    },
    'M25': {
      'ko': '부활과 영원한 생명을 싹틔우는 군주로서, 꺾이지 않는 재생과 새로운 도약의 기운을 전합니다.',
      'en': 'Sprouts eternal life after dormancy, empowering you with resilient leaps of renewal.',
      'ja': '復活と永遠の命を芽吹かせる王として、挫けぬ再生と飛躍の気運をもたらします。',
      'zh': '掌管轮回往复与谷物繁衍，赋予九死不悔之坚韧复生力量与更高跃升之气数。',
      'de': 'Keimt ewiges Leben aus der Tiefe und verleiht Kraft zu neuem Aufschwung.',
      'hi': 'अमरता और नए जीवन का प्रतीक, जो हर गिरावट के बाद फिर उठने की शक्ति देता है।',
    },
    'M26': {
      'ko': '기쁨과 풍요, 평화를 수호하는 묘신으로서, 가정의 화목을 지키고 상서로운 웃음을 가져다줍니다.',
      'en': 'Guards home hearths with feline grace, inviting harmonious laughter, peace, and abundance.',
      'ja': '歓喜と豊穣、平和を守護する神として、家庭の和合を保ち幸福の笑みをもたらします。',
      'zh': '护佑宅院安乐祥和之猫首女神，融洽门中骨肉亲缘，迎纳欢声笑语与丰裕资财。',
      'de': 'Wacht über das Heim und schenkt heitere Eintracht, Lachen und Wohlstand.',
      'hi': 'घर में सुख, हंसी और खुशहाली लाती हैं और परिवार के मेल-मिलाप की रक्षा करती हैं।',
    },
    'M27': {
      'ko': '진실의 무게를 저울에 다는 공정한 안내자로서, 올바른 판단과 평온한 영혼의 안식을 돕습니다.',
      'en': 'Balances hearts against the feather of truth, fostering sound judgment and tranquil minds.',
      'ja': '真実の重さを天秤で量る公正なる導き手として、正しき判断と魂の平穏を助けます。',
      'zh': '在真理天秤前审视心灵纯度，辅弼贤良明断秋毫，赐予灵魂终极安宁与慰藉。',
      'de': 'Wiegt Herzen gegen die Feder der Wahrheit und schenkt klares Urteil und Seelenfrieden.',
      'hi': 'सच्चाई के तराजू पर कर्मों को तौलता है और सही निर्णय व आत्मा को शांति देता है।',
    },
    'M28': {
      'ko': '어둠을 가르는 정의의 검과 수호의 방패로서, 모든 사악한 기운을 물리치고 안전하게 보호합니다.',
      'en': 'Shield of safety and sword of justice, driving away every dark menace to guard you securely.',
      'ja': '正義の剣と守護の盾で闇を払い、あらゆる邪悪な気配を退けて堅固に守ります。',
      'zh': '手按正义圣剑与不破神盾，荡平一切阴暗凶邪之气，保佑您周全平顺。',
      'de': 'Hält Schwert und Schild der Gerechtigkeit und schlägt jedes Unheil verlässlich zurück.',
      'hi': 'न्याय की तलवार और ढाल थामे सभी बुरी ताकतों को हराकर आपकी सुरक्षा करते हैं।',
    },
    'M29': {
      'ko': '기쁜 소식과 희망의 메시지를 전하는 천상 메신저로서, 반가운 인연과 행운의 서광을 알려 줍니다.',
      'en': 'Blows celestial clarions of glad tidings, announcing cherished bonds and rising dawn of fortune.',
      'ja': '喜ばしい知らせと希望のメッセージを届ける使者として、幸運の兆しを告げてくれます。',
      'zh': '传报莫大佳音与希望天音，昭告宿缘良朋如约而至，迎来满堂红霞之好运曙光。',
      'de': 'Kündet vom Anbruch froher Nachrichten und führt segensreiche Wendungen herbei.',
      'hi': 'खुशखबरी और आशा का संदेश लाते हैं और जीवन में नए भाग्य का सवेरा जगाते हैं।',
    },
    'M30': {
      'ko': '지친 여정과 상처받은 마음을 보듬는 치유의 천사로서, 온화한 위로와 건강한 회복을 선사합니다.',
      'en': 'Comforts exhausted steps and bruised hearts, bestowing restorative vigor and peaceful health.',
      'ja': '疲れた旅路と傷ついた心を包み込む治癒の大天使として、健やかな回復を贈ります。',
      'zh': '抚慰千里跋涉之疲乏与伤痕累累之行囊，赐予和风细雨般之神愈康复与慰藉。',
      'de': 'Heilt verletzte Seelen und stärkt den Körper mit heilsamer Genesungskraft.',
      'hi': 'कठिन रास्तों पर थके हुओं को संभालते हैं और तन-मन को पूर्ण स्वस्थ बनाते हैं।',
    },
    'M31': {
      'ko': '어둠을 사르는 지혜의 등대 천사로서, 혼란스러운 순간에 명확한 진리의 빛을 밝혀 줍니다.',
      'en': 'Burns like a lighthouse across murky confusion, revealing clear paths of pure truth.',
      'ja': '迷いと闇を焼き尽くす知恵の灯火として、混迷の時に真実の光を明瞭に照らし出します。',
      'zh': '如黑夜中卓立之高耸灯塔，在迷惘困惑之幽谷为前行者洞开明澈真理之光明大道。',
      'de': 'Leuchtet wie ein Fanal in dunklen Stunden und weist den klaren Pfad der Weisheit.',
      'hi': 'भ्रम और उलझनों के समय सत्य का प्रकाश फैलाते हैं और सही दिशा दिखाते हैं।',
    },
    'M32': {
      'ko': '한순간도 곁을 떠나지 않는 다정한 수호자로서, 일상의 모든 발걸음을 따스하게 지켜 줍니다.',
      'en': 'Never departs from your side, warmly attending every footstep in daily life with care.',
      'ja': '片時も傍を離れぬ優しき庇護者として、日々の歩みを温もりを込めて見守ります。',
      'zh': '晨昏相伴永不相离之慈爱保护神，用无微不至之柔情羽翼守护您的每一寸平凡日常。',
      'de': 'Weicht keinen Schritt von Ihrer Seite und bewacht jeden Tag mit liebevoller Fürsorge.',
      'hi': 'कभी भी आपका साथ नहीं छोड़ता और दिन-प्रतिदिन के हर कदम पर प्यार से रक्षा करता है।',
    },
    'M33': {
      'ko': '운명의 실타래를 아름답게 잣는 여신으로서, 헝클어진 인연을 풀고 고귀한 숙명을 엮어 줍니다.',
      'en': 'Spinning threads of golden destiny, untangling knotted ties to weave an exalted path.',
      'ja': '運命の糸車を美しく回す女神として、絡まりし絆を解きほぐし気高き宿命を織り成します。',
      'zh': '巧手拨弄宿命之经纬，为您解开纷乱无绪之结，编织出锦绣如画之尊贵人生篇章。',
      'de': 'Spinnen den Lebensfaden zu edlem Gewebe und lösen verstrickte Knoten des Schicksals.',
      'hi': 'भाग्य के धागों को सुंदर ढंग से बुनती हैं और उलझे हुए रिश्तों को सुलझाकर महान तकदीर बनाती हैं।',
    },
  };
}
